{*!
 * Fano Web Framework (https://fanoframework.github.io)
 *
 * @link      https://github.com/fanoframework/fano
 * @copyright Copyright (c) 2018 - 2020 Zamrony P. Juhara
 * @license   https://github.com/fanoframework/fano/blob/master/LICENSE (MIT)
 *}

(*! ---------------------------------------------
 * implementation unit that is included in fano.pas unit
 * This file is provided so we can use fano framework
 * by using only one uses to simplify things.
 *
 * @author Zamrony P. Juhara <zamronypj@yahoo.com>
 *-----------------------------------------------*)

{$INCLUDE Core/Implementations/implementations.inc}
{$INCLUDE DI/Implementations/implementations.inc}
{$INCLUDE Environment/Implementations/implementations.inc}
{$INCLUDE Dispatcher/Implementations/implementations.inc}
{$INCLUDE App/Implementations/implementations.inc}
{$INCLUDE Router/Implementations/implementations.inc}
{$INCLUDE Http/Implementations/implementations.inc}
{$INCLUDE Libs/Implementations/implementations.inc}
{$INCLUDE Error/Implementations/implementations.inc}
{$INCLUDE Config/Implementations/implementations.inc}
{$INCLUDE Middleware/Implementations/implementations.inc}
{$INCLUDE Mvc/Implementations/implementations.inc}
{$INCLUDE Security/Implementations/implementations.inc}
{$INCLUDE Sessions/Implementations/implementations.inc}
{$INCLUDE Db/Implementations/implementations.inc}
