{*!
 * Fano Web Framework (https://fanoframework.github.io)
 *
 * @link      https://github.com/fanoframework/fano
 * @copyright Copyright (c) 2018 - 2022 Zamrony P. Juhara
 * @license   https://github.com/fanoframework/fano/blob/master/LICENSE (MIT)
 *}

(*! ---------------------------------------------
 * unit interfaces that is included in fano.pas unit
 * This file is provided so we can use fano framework
 * by using only one uses to simplify things.
 *
 * @author Zamrony P. Juhara <zamronypj@yahoo.com>
 *-----------------------------------------------*)

{$INCLUDE Core/Contracts/interfaces.inc}
{$INCLUDE DI/Contracts/interfaces.inc}
{$INCLUDE Dispatcher/Contracts/interfaces.inc}
{$INCLUDE Environment/Contracts/interfaces.inc}
{$INCLUDE Error/Contracts/interfaces.inc}
{$INCLUDE App/Contracts/interfaces.inc}
{$INCLUDE Http/Contracts/interfaces.inc}
{$INCLUDE Router/Contracts/interfaces.inc}
{$INCLUDE Middleware/Contracts/interfaces.inc}
{$INCLUDE Config/Contracts/interfaces.inc}
{$INCLUDE Libs/Contracts/interfaces.inc}
{$INCLUDE Mvc/Contracts/interfaces.inc}
{$INCLUDE Security/Contracts/interfaces.inc}
{$INCLUDE Sessions/Contracts/interfaces.inc}
{$INCLUDE Db/Contracts/interfaces.inc}
