{*!
 * Fano Web Framework (https://fanoframework.github.io)
 *
 * @link      https://github.com/fanoframework/fano
 * @copyright Copyright (c) 2018 - 2020 Zamrony P. Juhara
 * @license   https://github.com/fanoframework/fano/blob/master/LICENSE (MIT)
 *}

{------------ Begin FastCGI-related------------------}
TFcgiAbortRequest = FcgiAbortRequest.TFcgiAbortRequest;
TFcgiBeginRequest = FcgiBeginRequest.TFcgiBeginRequest;
TFcgiData = FcgiData.TFcgiData;
TFcgiEndRequest = FcgiEndRequest.TFcgiEndRequest;
TFcgiGetValues = FcgiGetValues.TFcgiGetValues;
TFcgiGetValuesResult = FcgiGetValuesResult.TFcgiGetValuesResult;
TFcgiStdIn = FcgiStdIn.TFcgiStdIn;
TFcgiStdOut = FcgiStdOut.TFcgiStdOut;
TFcgiStdErr = FcgiStdErr.TFcgiStdErr;
TFcgiUnknownType = FcgiUnknownType.TFcgiUnknownType;

TFcgiAbortRequestFactory = FcgiAbortRequestFactory.TFcgiAbortRequestFactory;
TFcgiBeginRequestFactory = FcgiBeginRequestFactory.TFcgiBeginRequestFactory;
TFcgiDataFactory = FcgiDataFactory.TFcgiDataFactory;
TFcgiEndRequestFactory = FcgiEndRequestFactory.TFcgiEndRequestFactory;
TFcgiGetValuesFactory = FcgiGetValuesFactory.TFcgiGetValuesFactory;
TFcgiGetValuesResultFactory = FcgiGetValuesResultFactory.TFcgiGetValuesResultFactory;
TFcgiStdInFactory = FcgiStdInFactory.TFcgiStdInFactory;
TFcgiStdOutFactory = FcgiStdOutFactory.TFcgiStdOutFactory;
TFcgiStdErrFactory = FcgiStdErrFactory.TFcgiStdErrFactory;
TFcgiUnknownTypeFactory = FcgiUnknownTypeFactory.TFcgiUnknownTypeFactory;

TFcgiStdOutWriter = FcgiStdOutWriterImpl.TFcgiStdOutWriter;
TFcgiRequestManager = FcgiRequestManagerImpl.TFcgiRequestManager;
TFcgiFrameParser = FcgiFrameParserImpl.TFcgiFrameParser;
TFcgiProcessor = FcgiProcessorImpl.TFcgiProcessor;
{------------ End FastCGI-related------------------}
