{*!
 * Fano Web Framework (https://fanoframework.github.io)
 *
 * @link      https://github.com/fanoframework/fano
 * @copyright Copyright (c) 2018 - 2021 Zamrony P. Juhara
 * @license   https://github.com/fanoframework/fano/blob/master/LICENSE (MIT)
 *}

{------------ Begin uwsgi-related------------------}
TUwsgiStdOutWriter = UwsgiStdOutWriterImpl.TUwsgiStdOutWriter;
TUwsgiParser = UwsgiParserImpl.TUwsgiParser;
TUwsgiProcessor = UwsgiProcessorImpl.TUwsgiProcessor;
{------------ End uwsgi-related------------------}
