{*!
 * Fano Web Framework (https://fanoframework.github.io)
 *
 * @link      https://github.com/fanoframework/fano
 * @copyright Copyright (c) 2018 - 2021 Zamrony P. Juhara
 * @license   https://github.com/fanoframework/fano/blob/master/LICENSE (MIT)
 *}

(*! ---------------------------------------------
 * list of cors units in security
 * that is included in implementations.inc
 *
 * @author Zamrony P. Juhara <zamronypj@yahoo.com>
 *-----------------------------------------------*)

CorsImpl,
CorsConfigImpl,
NullCorsImpl,
CorsMiddlewareImpl,
BaseCorsMiddlewareFactoryImpl,
CorsMiddlewareFactoryImpl,
NullCorsMiddlewareFactoryImpl,
