{*!
 * Fano Web Framework (https://fanoframework.github.io)
 *
 * @link      https://github.com/fanoframework/fano
 * @copyright Copyright (c) 2018 - 2021 Zamrony P. Juhara
 * @license   https://github.com/fanoframework/fano/blob/master/LICENSE (MIT)
 *}

(*! ---------------------------------------------
 * implementation units for Libs/Protocol
 * that is included in fano.pas unit
 *
 * @author Zamrony P. Juhara <zamronypj@yahoo.com>
 *-----------------------------------------------*)


{$INCLUDE FastCGI/implementations.inc}
{$INCLUDE SCGI/implementations.inc}
{$INCLUDE Uwsgi/implementations.inc}
{$INCLUDE Http/implementations.inc}
