{*!
 * Fano Web Framework (https://fanoframework.github.io)
 *
 * @link      https://github.com/fanoframework/fano
 * @copyright Copyright (c) 2018 - 2022 Zamrony P. Juhara
 * @license   https://github.com/fanoframework/fano/blob/master/LICENSE (MIT)
 *}

HttpSvrConfigTypes,

{$INCLUDE Libmicrohttpd/implementations.inc}
{$INCLUDE Fpweb/implementations.inc}
{$INCLUDE Indy/implementations.inc}
{$INCLUDE Moremore/implementations.inc}
