{*!
 * Fano Web Framework (https://fanoframework.github.io)
 *
 * @link      https://github.com/fanoframework/fano
 * @copyright Copyright (c) 2018 - 2020 Zamrony P. Juhara
 * @license   https://github.com/fanoframework/fano/blob/master/LICENSE (MIT)
 *}

{------------ Begin libmicrohttpd-related------------------}
TMhdSvrConfig = MhdSvrConfigTypes.TMhdSvrConfig;
TMhdAppServiceProvider = MhdAppServiceProviderImpl.TMhdAppServiceProvider;
TMhdStdOutWriter = MhdStdOutWriterImpl.TMhdStdOutWriter;
TMhdProcessor = MhdProcessorImpl.TMhdProcessor;
{------------ End libmicrohttpd-related------------------}
