{*!
 * Fano Web Framework (https://fanoframework.github.io)
 *
 * @link      https://github.com/fanoframework/fano
 * @copyright Copyright (c) 2018 - 2021 Zamrony P. Juhara
 * @license   https://github.com/fanoframework/fano/blob/master/LICENSE (MIT)
 *}

{------------ Begin libmicrohttpd-related------------------}
{$IFDEF LIBMICROHTTPD}
TMhdSvrConfig = MhdSvrConfigTypes.TMhdSvrConfig;
TMhdAppServiceProvider = MhdAppServiceProviderImpl.TMhdAppServiceProvider;
TMhdStdOutWriter = MhdStdOutWriterImpl.TMhdStdOutWriter;
TMhdProcessor = MhdProcessorImpl.TMhdProcessor;
{$ENDIF}
{------------ End libmicrohttpd-related------------------}

{------------ Begin wchttpserver-related------------------}
{$IFDEF USE_WCHTTPSERVER}
TWcHttpServerProcessor = WcHttpServerProcessorImpl.TWcHttpServerProcessor;
{$ENDIF}
{------------ End wchttpserver-related------------------}
{------------ Begin TFpHttpServer-related------------------}
TFpwebSvrConfig = FpwebSvrConfigTypes.TFpwebSvrConfig;
TFpwebAppServiceProvider = FpwebAppServiceProviderImpl.TFpwebAppServiceProvider;
TFpwebStdOutWriter = FpwebStdOutWriterImpl.TFpwebStdOutWriter;
TFpwebRequest = FpwebRequestImpl.TFpwebRequest;
TFpwebRequestFactory = FpwebRequestFactoryImpl.TFpwebRequestFactory;
TFpwebProcessor = FpwebProcessorImpl.TFpwebProcessor;
{------------ End TFpHttpServer-related------------------}
