{*!
 * Fano Web Framework (https://fanoframework.github.io)
 *
 * @link      https://github.com/fanoframework/fano
 * @copyright Copyright (c) 2018 - 2021 Zamrony P. Juhara
 * @license   https://github.com/fanoframework/fano/blob/master/LICENSE (MIT)
 *}

THttpSvrConfig = HttpSvrConfigTypes.THttpSvrConfig;

{$INCLUDE Libmicrohttpd/libs.aliases.inc}
{$INCLUDE Fpweb/libs.aliases.inc}
{$INCLUDE Indy/libs.aliases.inc}
{$INCLUDE WCHttpServer/libs.aliases.inc}

