THeadersFactory = HeadersFactoryImpl.THeadersFactory;
TRequest = RequestImpl.TRequest;
TDecoratorRequest = DecoratorRequestImpl.TDecoratorRequest;
TJsonRequest = JsonRequestImpl.TJsonRequest;
TResponse = ResponseImpl.TResponse;
TJsonResponse = JsonResponseImpl.TJsonResponse;
TBinaryResponse = BinaryResponseImpl.TBinaryResponse;
TRedirectResponse = RedirectResponseImpl.TRedirectResponse;
TNotModifiedResponse = NotMOdifiedResponseImpl.TNotModifiedResponse;
TResponseStream = ResponseStreamImpl.TResponseStream;
TUploadedFile = UploadedFileImpl.TUploadedFile;
TUploadedFileCollection = UploadedFileCollectionImpl.TUploadedFileCollection;

EInvalidRequest = EInvalidRequestImpl.EInvalidRequest;
EInvalidUploadedFile = EInvalidUploadedFileImpl.EInvalidUploadedFile;
EInvalidMethod = EInvalidMethodImpl.EInvalidMethod;
ENotFound = ENotFoundImpl.ENotFound;
EForbidden = EForbiddenImpl.EForbidden;
EUnauthorized = EUnauthorizedImpl.EUnauthorized;

TCookie = CookieImpl.TCookie;
TCookieFactory = CookieFactoryImpl.TCookieFactory;

TUri = UriImpl.TUri;
