{*!
 * Fano Web Framework (https://fanoframework.github.io)
 *
 * @link      https://github.com/fanoframework/fano
 * @copyright Copyright (c) 2018 - 2022 Zamrony P. Juhara
 * @license   https://github.com/fanoframework/fano/blob/master/LICENSE (MIT)
 *}

(*! ---------------------------------------------
 * alias for implementation in security
 * that is included in implementations.aliases.inc
 *
 * @author Zamrony P. Juhara <zamronypj@yahoo.com>
 *-----------------------------------------------*)

TNoPoweredByMiddleware = NoPoweredByMiddlewareImpl.TNoPoweredByMiddleware;
TNoPoweredByMiddlewareFactory = NoPoweredByMiddlewareFactoryImpl.TNoPoweredByMiddlewareFactory;
