{*!
 * Fano Web Framework (https://fanoframework.github.io)
 *
 * @link      https://github.com/fanoframework/fano
 * @copyright Copyright (c) 2018 - 2022 Zamrony P. Juhara
 * @license   https://github.com/fanoframework/fano/blob/master/LICENSE (MIT)
 *}

(*! ---------------------------------------------
 * unit interfaces that is included in mvc.aliases.inc
 *
 * @author Zamrony P. Juhara <zamronypj@yahoo.com>
 *-----------------------------------------------*)

IView = ViewIntf.IView;
IViewPartial = ViewPartialIntf.IViewPartial;
IViewParameters = ViewParametersIntf.IViewParameters;
ITemplateParser = TemplateParserIntf.ITemplateParser;
IViewStack = ViewStackIntf.IViewStack;
IViewPush = ViewPushIntf.IViewPush;
