TSimpleTemplateParserFactory = SimpleTemplateParserFactoryImpl.TSimpleTemplateParserFactory;
TTemplateParserFactory = TemplateParserFactoryImpl.TTemplateParserFactory;
TViewParametersFactory = ViewParametersFactoryImpl.TViewParametersFactory;
TTemplateFileView = TemplateFileViewImpl.TTemplateFileView;

TView = ViewImpl.TView;
TCompositeView = CompositeViewImpl.TCompositeView;
TNullView = NullViewImpl.TNullView;
TViewPartial = ViewPartialImpl.TViewPartial;
TViewPartialFactory = ViewPartialFactoryImpl.TViewPartialFactory;
