TSimpleTemplateParserFactory = SimpleTemplateParserFactoryImpl.TSimpleTemplateParserFactory;
TTemplateParserFactory = TemplateParserFactoryImpl.TTemplateParserFactory;
TNullTemplateParserFactory = NullTemplateParserFactoryImpl.TNullTemplateParserFactory;

TSimpleTemplateParser = SimpleTemplateParserImpl.TSimpleTemplateParser;
TTemplateParser = TemplateParserImpl.TTemplateParser;
TNullTemplateParser = NullTemplateParserImpl.TNullTemplateParser;

TViewParametersFactory = ViewParametersFactoryImpl.TViewParametersFactory;
TTemplateFileView = TemplateFileViewImpl.TTemplateFileView;

TView = ViewImpl.TView;
TCompositeView = CompositeViewImpl.TCompositeView;
TNullView = NullViewImpl.TNullView;
TViewPartial = ViewPartialImpl.TViewPartial;
TViewPartialFactory = ViewPartialFactoryImpl.TViewPartialFactory;
