{*!
 * Fano Web Framework (https://fanoframework.github.io)
 *
 * @link      https://github.com/fanoframework/fano
 * @copyright Copyright (c) 2018 - 2021 Zamrony P. Juhara
 * @license   https://github.com/fanoframework/fano/blob/master/LICENSE (MIT)
 *}

(*! ---------------------------------------------
 * consts declaration that is included in fano.pas unit
 * This file is provided so we can use fano framework
 * by using only one uses to simplify things.
 *
 * @author Zamrony P. Juhara <zamronypj@yahoo.com>
 *-----------------------------------------------*)

logEmergency = LogLevelTypes.logEmergency;
logAlert = LogLevelTypes.logAlert;
logCritical = LogLevelTypes.logCritical;
logError = LogLevelTypes.logError;
logWarning = LogLevelTypes.logWarning;
logDebug = LogLevelTypes.logDebug;
logInfo = LogLevelTypes.logInfo;
logNotice = LogLevelTypes.logNotice;
