TPlaceholder = PlaceholderTypes.TPlaceholder;
TArrayOfPlaceholders = PlaceholderTypes.TArrayOfPlaceholders;
TKeyValue = KeyValueTypes.TKeyValue;
PKeyValue = KeyValueTypes.PKeyValue;
TArrayOfKeyValue = KeyValueTypes.TArrayOfKeyValue;
TNullSerializeable = NullSerializeableImpl.TNullSerializeable;
TStringSerializeable = StringSerializeableImpl.TStringSerializeable;
TJsonSerializeable = JsonSerializeableImpl.TJsonSerializeable;
TExceptionSerializeable = ExceptionSerializeableImpl.TExceptionSerializeable;
THashList = HashListImpl.THashList;
TCompositeList = CompositeListImpl.TCompositeList;
TCompositeReadOnlyList = CompositeReadOnlyListImpl.TCompositeReadOnlyList;

EKeyNotFound = EKeyNotFoundImpl.EKeyNotFound;
EIndexOutOfBound = EIndexOutOfBoundImpl.EIndexOutOfBound;
