TPlaceholder = PlaceholderTypes.TPlaceholder;
TArrayOfPlaceholders = PlaceholderTypes.TArrayOfPlaceholders;
TKeyValue = KeyValueTypes.TKeyValue;
TArrayOfKeyValue = KeyValueTypes.TArrayOfKeyValue;
TNullSerializeable = NullSerializeableImpl.TNullSerializeable;
TStringSerializeable = StringSerializeableImpl.TStringSerializeable;
THashList = HashListImpl.THashList;
TCompositeList = CompositeListImpl.TCompositeList;

EKeyNotFound = EKeyNotFoundImpl.EKeyNotFound;
EIndexOutOfBound = EIndexOutOfBoundImpl.EIndexOutOfBound;
