{*!
 * Fano Web Framework (https://fanoframework.github.io)
 *
 * @link      https://github.com/fanoframework/fano
 * @copyright Copyright (c) 2018 - 2021 Zamrony P. Juhara
 * @license   https://github.com/fanoframework/fano/blob/master/LICENSE (MIT)
 *}

{------------ Begin Null http client related------------------}
TNullHttpClient = NullHttpClientImpl.TNullHttpClient;
TNullHttpClientFactory = NullHttpClientFactoryImpl.TNullHttpClientFactory;
{------------ End Null http client related------------------}
