{*!
 * Fano Web Framework (https://fanoframework.github.io)
 *
 * @link      https://github.com/fanoframework/fano
 * @copyright Copyright (c) 2018 - 2022 Zamrony P. Juhara
 * @license   https://github.com/fanoframework/fano/blob/master/LICENSE (MIT)
 *}

{------------ Begin TFpHttpServer-related------------------}
TFpwebSvrConfig = FpwebSvrConfigTypes.TFpwebSvrConfig;
TFpwebAppServiceProvider = FpwebAppServiceProviderImpl.TFpwebAppServiceProvider;
TFpwebStdOutWriter = FpwebStdOutWriterImpl.TFpwebStdOutWriter;
TFpwebRequest = FpwebRequestImpl.TFpwebRequest;
TFpwebRequestFactory = FpwebRequestFactoryImpl.TFpwebRequestFactory;
TFpwebProcessor = FpwebProcessorImpl.TFpwebProcessor;
{------------ End TFpHttpServer-related------------------}
