{*!
 * Fano Web Framework (https://fanoframework.github.io)
 *
 * @link      https://github.com/fanoframework/fano
 * @copyright Copyright (c) 2018 - 2022 Zamrony P. Juhara
 * @license   https://github.com/fanoframework/fano/blob/master/LICENSE (MIT)
 *}

{------------ Begin TIdHTTPServer-related------------------}
{$IFDEF USE_INDY}
TIndyAppServiceProvider = IndyAppServiceProviderImpl.TIndyAppServiceProvider;
TIndyStdOutWriter = IndyStdOutWriterImpl.TIndyStdOutWriter;
TIndyProcessor = IndyProcessorImpl.TIndyProcessor;
{$ENDIF}
{------------ End TIdHttpServer-related------------------}
