THeadersFactory = HeadersFactoryImpl.THeadersFactory;
TRequest = RequestImpl.TRequest;
TResponse = ResponseImpl.TResponse;
TJsonResponse = JsonResponseImpl.TJsonResponse;
TBinaryResponse = BinaryResponseImpl.TBinaryResponse;
TResponseStream = ResponseStreamImpl.TResponseStream;
TUploadedFile = UploadedFileImpl.TUploadedFile;
TUploadedFileCollection = UploadedFileCollectionImpl.TUploadedFileCollection;

EInvalidRequest = EInvalidRequestImpl.EInvalidRequest;
EInvalidUploadedFile = EInvalidUploadedFileImpl.EInvalidUploadedFile;
