{*!
 * Fano Web Framework (https://fanoframework.github.io)
 *
 * @link      https://github.com/fanoframework/fano
 * @copyright Copyright (c) 2018 - 2020 Zamrony P. Juhara
 * @license   https://github.com/fanoframework/fano/blob/master/LICENSE (MIT)
 *}

(*! ---------------------------------------------
 * implementation units for security
 * that is included in fano.pas unit
 *
 * @author Zamrony P. Juhara <zamronypj@yahoo.com>
 *-----------------------------------------------*)

{$INCLUDE Validations/implementations.inc}
{$INCLUDE Sanitations/implementations.inc}
{$INCLUDE Cors/implementations.inc}
{$INCLUDE Csrf/implementations.inc}
{$INCLUDE Auth/implementations.inc}
{$INCLUDE Xss/implementations.inc}
{$INCLUDE FrameGuard/implementations.inc}
{$INCLUDE PasswordHash/implementations.inc}
