{*!
 * Fano Web Framework (https://fanoframework.github.io)
 *
 * @link      https://github.com/fanoframework/fano
 * @copyright Copyright (c) 2018 - 2022 Zamrony P. Juhara
 * @license   https://github.com/fanoframework/fano/blob/master/LICENSE (MIT)
 *}

(*! ---------------------------------------------
 * alias for implementation in security
 * that is included in implementations.aliases.inc
 *
 * @author Zamrony P. Juhara <zamronypj@yahoo.com>
 *-----------------------------------------------*)

{$INCLUDE Validations/aliases.inc}
{$INCLUDE Sanitations/aliases.inc}
{$INCLUDE Cors/aliases.inc}
{$INCLUDE Csrf/aliases.inc}
{$INCLUDE Auth/aliases.inc}
{$INCLUDE Xss/aliases.inc}
{$INCLUDE FrameGuard/aliases.inc}
{$INCLUDE PasswordHash/aliases.inc}
{$INCLUDE Jwt/aliases.inc}
{$INCLUDE Csp/aliases.inc}
