{*!
 * Fano Web Framework (https://fanoframework.github.io)
 *
 * @link      https://github.com/fanoframework/fano
 * @copyright Copyright (c) 2018 Zamrony P. Juhara
 * @license   https://github.com/fanoframework/fano/blob/master/LICENSE (MIT)
 *}

(*! ---------------------------------------------
 * alias for validators implementation in security
 * that is included in security.aliases.inc
 *
 * @author Zamrony P. Juhara <zamronypj@yahoo.com>
 *-----------------------------------------------*)

TBaseValidator = BaseValidatorImpl.TBaseValidator;
TAlphaNumSpaceValidator = AlphaNumSpaceValidatorImpl.TAlphaNumSpaceValidator;
TAlphaNumValidator = AlphaNumValidatorImpl.TAlphaNumValidator;
TCompositeValidator = CompositeValidatorImpl.TCompositeValidator;
TIntegerValidator = IntegerValidatorImpl.TIntegerValidator;
TMinIntegerValidator = MinIntegerValidatorImpl.TMinIntegerValidator;
TMaxIntegerValidator = MaxIntegerValidatorImpl.TMaxIntegerValidator;
TRegexValidator = RegexValidatorImpl.TRegexValidator;
TRequiredValidator = RequiredValidatorImpl.TRequiredValidator;
