{*!
 * Fano Web Framework (https://fanoframework.github.io)
 *
 * @link      https://github.com/fanoframework/fano
 * @copyright Copyright (c) 2018 Zamrony P. Juhara
 * @license   https://github.com/fanoframework/fano/blob/master/LICENSE (MIT)
 *}

{------------ ClamAV antivirus related------------------}
{$IFDEF LIBCLAMAV}
ClamAvImpl,
EClamAvImpl,
{$ENDIF}
{------------ End ClamAV antivirus related------------------}

NullAvImpl,
