{*!
 * Fano Web Framework (https://fanoframework.github.io)
 *
 * @link      https://github.com/fanoframework/fano
 * @copyright Copyright (c) 2018 - 2022 Zamrony P. Juhara
 * @license   https://github.com/fanoframework/fano/blob/master/LICENSE (MIT)
 *}

{------------ Begin ClamAV antivirus related------------------}
EClamAv = EClamAvImpl.EClamAv;
TLocalClamdAv = LocalClamdAvImpl.TLocalClamdAv;
TClamdAv = ClamdAvImpl.TClamdAv;
{------------ End ClamAV antivirus related------------------}

TNullAv = NullAvImpl.TNullAv;
