{*!
 * Fano Web Framework (https://fanoframework.github.io)
 *
 * @link      https://github.com/fanoframework/fano
 * @copyright Copyright (c) 2018 - 2022 Zamrony P. Juhara
 * @license   https://github.com/fanoframework/fano/blob/master/LICENSE (MIT)
 *}

(*! ---------------------------------------------
 * alias for implementation in HTTP Strict Transport Security Middleware
 * that is included in implementations.aliases.inc
 *
 * @author Zamrony P. Juhara <zamronypj@yahoo.com>
 *-----------------------------------------------*)

THstsConfig = HstsConfig.THstsConfig;
THstsMiddleware = HstsMiddlewareImpl.THstsMiddleware;
THstsMiddlewareFactory = HstsMiddlewareFactoryImpl.THstsMiddlewareFactory;
