{*!
 * Fano Web Framework (https://fanoframework.github.io)
 *
 * @link      https://github.com/fanoframework/fano
 * @copyright Copyright (c) 2018 - 2021 Zamrony P. Juhara
 * @license   https://github.com/fanoframework/fano/blob/master/LICENSE (MIT)
 *}

IClientBrowser = ClientBrowserIntf.IClientBrowser;
IClientDevice = ClientDeviceIntf.IClientDevice;
IClientOS = ClientOsIntf.IClientOS;
IUserAgent = UserAgentIntf.IUserAgent;
