{*!
 * Fano Web Framework (https://fanoframework.github.io)
 *
 * @link      https://github.com/fanoframework/fano
 * @copyright Copyright (c) 2018 - 2020 Zamrony P. Juhara
 * @license   https://github.com/fanoframework/fano/blob/master/LICENSE (MIT)
 *}

(*! ---------------------------------------------
 * list of xss units in security
 * that is included in implementations.inc
 *
 * @author Zamrony P. Juhara <zamronypj@yahoo.com>
 *-----------------------------------------------*)
Pbkdf2PasswHashImpl,
Pbkdf2PasswHashFactoryImpl,
Argon2iPasswHashImpl,
Argon2iPasswHashFactoryImpl,
Sha2_256PasswHashImpl,
Sha2_512PasswHashImpl,
Sha2PasswHashFactoryImpl,
