{*!
 * Fano Web Framework (https://fanoframework.github.io)
 *
 * @link      https://github.com/fanoframework/fano
 * @copyright Copyright (c) 2018 - 2022 Zamrony P. Juhara
 * @license   https://github.com/fanoframework/fano/blob/master/LICENSE (MIT)
 *}

(*! ---------------------------------------------
 * list of xss units in security
 * that is included in implementations.inc
 *
 * @author Zamrony P. Juhara <zamronypj@yahoo.com>
 *-----------------------------------------------*)
Pbkdf2PasswordHashImpl,
Pbkdf2PasswordHashFactoryImpl,
Argon2iPasswordHashImpl,
Argon2iPasswordHashFactoryImpl,
ScryptPasswordHashImpl,
ScryptPasswordHashFactoryImpl,
Sha2_256PasswordHashImpl,
Sha2_512PasswordHashImpl,
Sha2PasswordHashFactoryImpl,
