{*!
 * Fano Web Framework (https://fanoframework.github.io)
 *
 * @link      https://github.com/fanoframework/fano
 * @copyright Copyright (c) 2018 Zamrony P. Juhara
 * @license   https://github.com/fanoframework/fano/blob/master/LICENSE (MIT)
 *}

(*! ---------------------------------------------
 * alias for interface in security
 * that is included in fano.pas unit
 *
 * @author Zamrony P. Juhara <zamronypj@yahoo.com>
 *-----------------------------------------------*)

ICsrf = CsrfIntf.ICsrf;
ISanitizer = SanitizerIntf.ISanitizer;
IValidator = ValidatorIntf.IValidator;
IValidatorCollection = ValidatorCollectionIntf.IValidatorCollection;
IValidationRules = ValidationRulesIntf.IValidationRules;
IRequestValidator = RequestValidatorIntf.IRequestValidator;

{$INCLUDE cors.aliases.inc}
