{*!
 * Fano Web Framework (https://fanoframework.github.io)
 *
 * @link      https://github.com/fanoframework/fano
 * @copyright Copyright (c) 2018 - 2020 Zamrony P. Juhara
 * @license   https://github.com/fanoframework/fano/blob/master/LICENSE (MIT)
 *}

(*! ---------------------------------------------
 * alias for interface in security
 * that is included in fano.pas unit
 *
 * @author Zamrony P. Juhara <zamronypj@yahoo.com>
 *-----------------------------------------------*)

{$INCLUDE Csrf/aliases.inc}
{$INCLUDE Sanitations/aliases.inc}
{$INCLUDE Validations/aliases.inc}
{$INCLUDE Cors/aliases.inc}
{$INCLUDE Auth/aliases.inc}
{$INCLUDE PasswordHash/aliases.inc}
{$INCLUDE Jwt/aliases.inc}
