{*!
 * Fano Web Framework (https://fanoframework.github.io)
 *
 * @link      https://github.com/fanoframework/fano
 * @copyright Copyright (c) 2018 - 2021 Zamrony P. Juhara
 * @license   https://github.com/fanoframework/fano/blob/master/LICENSE (MIT)
 *}

TSimpleTemplateParserFactory = SimpleTemplateParserFactoryImpl.TSimpleTemplateParserFactory;
TTemplateParserFactory = TemplateParserFactoryImpl.TTemplateParserFactory;
TNullTemplateParserFactory = NullTemplateParserFactoryImpl.TNullTemplateParserFactory;

TSimpleTemplateParser = SimpleTemplateParserImpl.TSimpleTemplateParser;
TTemplateParser = TemplateParserImpl.TTemplateParser;
TNullTemplateParser = NullTemplateParserImpl.TNullTemplateParser;

TViewParameters = ViewParametersImpl.TViewParameters;
TViewParametersFactory = ViewParametersFactoryImpl.TViewParametersFactory;
TNullViewParameters = NullViewParametersImpl.TNullViewParameters;
TNullViewParametersFactory = NullViewParametersFactoryImpl.TNullViewParametersFactory;
TCompositeViewParameters = CompositeViewParametersImpl.TCompositeViewParameters;

TView = ViewImpl.TView;
TStaticView = StaticViewImpl.TStaticView;
TCompositeView = CompositeViewImpl.TCompositeView;
TTemplateView = TemplateViewImpl.TTemplateView;
TGroupView = GroupViewImpl.TGroupView;
TNullView = NullViewImpl.TNullView;
TNullViewFactory = NullViewFactoryImpl.TNullViewFactory;
TViewPartial = ViewPartialImpl.TViewPartial;
TStrViewPartial = StrViewPartialImpl.TStrViewPartial;
TViewPartialFactory = ViewPartialFactoryImpl.TViewPartialFactory;
TStrViewPartialFactory = StrViewPartialFactoryImpl.TStrViewPartialFactory;

TViewStack = ViewStackImpl.TViewStack;
TViewStackFactory = ViewStackFactoryImpl.TViewStackFactory;