{*!
 * Fano Web Framework (https://fanoframework.github.io)
 *
 * @link      https://github.com/fanoframework/fano
 * @copyright Copyright (c) 2018 - 2021 Zamrony P. Juhara
 * @license   https://github.com/fanoframework/fano/blob/master/LICENSE (MIT)
 *}

(*! ---------------------------------------------
 * implementation units for dispatcher
 * that is included in fano.pas unit
 *
 * @author Zamrony P. Juhara <zamronypj@yahoo.com>
 *-----------------------------------------------*)

DispatcherImpl,
SimpleDispatcherImpl,
VerbTunnellingDispatcherImpl,
XDispatcherImpl,
XSimpleDispatcherImpl,
MwExecDispatcherImpl,
MaintenanceModeDispatcherImpl,

DispatcherFactoryImpl,
SimpleDispatcherFactoryImpl,
SessionDispatcherFactoryImpl,
VerbTunnellingDispatcherFactoryImpl,
XDispatcherFactoryImpl,
XSimpleDispatcherFactoryImpl,
MwExecDispatcherFactoryImpl,
MaintenanceModeDispatcherFactoryImpl,

EInvalidDispatcherImpl,
ERouteHandlerNotFoundImpl,

RequestResponseFactoryImpl,
FcgiRequestResponseFactoryImpl,
VerbTunnellingRequestResponseFactoryImpl,

FuncRequestHandlerImpl,
MethodRequestHandlerImpl,