{*!
 * Fano Web Framework (https://fanoframework.github.io)
 *
 * @link      https://github.com/fanoframework/fano
 * @copyright Copyright (c) 2018 Zamrony P. Juhara
 * @license   https://github.com/fanoframework/fano/blob/master/LICENSE (MIT)
 *}

{------------ Begin TFpHttpClient-related------------------}

TFpcHttpGet = HttpFpcGetImpl.TFpcHttpGet;
TFpcHttpGetFactory = FpcHttpGetFactoryImpl.TFpcHttpGetFactory;

TFpcHttpFpcPost = FpcHttpPostImpl.TFpcHttpPost;
TFpcHttpPostFactory = FpcHttpPostFactoryImpl.TFpcHttpPostFactory;

TFpcHttpPut = FpcHttpPutImpl.TFpcHttpPut;
TFpcHttpPutFactory = FpcHttpPutFactoryImpl.TFpcHttpPutFactory;

TFpcHttpDelete = FpcHttpDeleteImpl.TFpcHttpDelete;
TFpcHttpDeleteFactory = FpcHttpDeleteFactoryImpl.TFpcHttpDeleteFactory;

TFpcHttpHead = FpcHttpHeadImpl.TFpcHttpHead;
TFpcHttpHeadFactory = FpcHttpHeadFactoryImpl.TFpcHttpHeadFactory;
{------------ End TFPHttpClient-related------------------}
