TJsonFileConfig = JsonFileConfigImpl.TJsonFileConfig;
TIniFileConfig = IniFileConfigImpl.TIniFileConfig;

TJsonStringConfig = JsonStringConfigImpl.TJsonStringConfig;
TIniStringConfig = IniStringConfigImpl.TIniStringConfig;

TEnvConfig = EnvConfigImpl.TEnvConfig;
TNullConfig = NullConfigImpl.TNullConfig;
TCompositeConfig = CompositeConfigImpl.TCompositeConfig;

TJsonFileConfigFactory = JsonFileConfigFactoryImpl.TJsonFileConfigFactory;
TIniFileConfigFactory = IniFileConfigFactoryImpl.TIniFileConfigFactory;

TJsonStringConfigFactory = JsonStringConfigFactoryImpl.TJsonStringConfigFactory;
TIniStringConfigFactory = IniStringConfigFactoryImpl.TIniStringConfigFactory;

TEnvConfigFactory = EnvConfigFactoryImpl.TEnvConfigFactory;
TNullConfigFactory = NullConfigFactoryImpl.TNullConfigFactory;
TCompositeConfigFactory = CompositeConfigFactoryImpl.TCompositeConfigFactory;
