IOutputBuffer = OutputBufferIntf.IOutputBuffer;
ILogger = LoggerIntf.ILogger;
IFileReader = FileReaderIntf.IFileReader;
IStreamAdapter = StreamAdapterIntf.IStreamAdapter;
IStdIn = StdInIntf.IStdIn;
IStdOut = StdOutIntf.IStdOut;
IStdErr = StdErrIntf.IStdErr;
IStdInStreamAware = StdInStreamAwareIntf.IStdInStreamAware;

IHttpClientHandleAware = HttpClientHandleAwareIntf.IHttpClientHandleAware;
IHttpClientHeaders = HttpClientHeadersIntf.IHttpClientHeaders;
IHttpGetClient = HttpGetClientIntf.IHttpGetClient;
IHttpPostClient = HttpPostClientIntf.IHttpPostClient;
IHttpPutClient = HttpPutClientIntf.IHttpPutClient;
IHttpDeleteClient = HttpDeleteClientIntf.IHttpDeleteClient;
IHttpHeadClient = HttpHeadClientIntf.IHttpHeadClient;

IKeyValuePair = KeyValuePairIntf.IKeyValuePair;

IRunnableWithDataNotif = RunnableWithDataNotifIntf.IRunnableWithDataNotif;

IFcgiRecord = FcgiRecordIntf.IFcgiRecord;
IFcgiRecordFactory = FcgiRecordFactoryIntf.IFcgiRecordFactory;
IFcgiRequest = FcgiRequestIntf.IFcgiRequest;
IFcgiRequestManager = FcgiRequestManagerIntf.IFcgiRequestManager;
IFcgiFrameParser = FcgiFrameParserIntf.IFcgiFrameParser;

IProtocolProcessor = ProtocolProcessorIntf.IProtocolProcessor;
IReadyListener = ReadyListenerIntf.IReadyListener;

IRegex = RegexIntf.IRegex;
