{*!
 * Fano Web Framework (https://fanoframework.github.io)
 *
 * @link      https://github.com/fanoframework/fano
 * @copyright Copyright (c) 2018 - 2021 Zamrony P. Juhara
 * @license   https://github.com/fanoframework/fano/blob/master/LICENSE (MIT)
 *}

TAbstractLogger = AbstractLoggerImpl.TAbstractLogger;
TFileLogger = FileLoggerImpl.TFileLogger;
TFileLoggerFactory = FileLoggerFactoryImpl.TFileLoggerFactory;
TNullLogger = NullLoggerImpl.TNullLogger;
TNullLoggerFactory = NullLoggerFactoryImpl.TNullLoggerFactory;
TCompositeLogger = CompositeLoggerImpl.TCompositeLogger;
TCompositeLoggerFactory = CompositeLoggerFactoryImpl.TCompositeLoggerFactory;
TSegregatedLogger = SegregatedLoggerImpl.TSegregatedLogger;
TSegregatedLoggerFactory = SegregatedLoggerFactoryImpl.TSegregatedLoggerFactory;
TStdOutLogger = StdOutLoggerImpl.TStdOutLogger;
TStdOutLoggerFactory = StdOutLoggerFactoryImpl.TStdOutLoggerFactory;
TStdErrLogger = StdErrLoggerImpl.TStdErrLogger;
TStdErrLoggerFactory = StdErrLoggerFactoryImpl.TStdErrLoggerFactory;
TSysLogLogger = SysLogLoggerImpl.TSysLogLogger;
TSysLogLoggerFactory = SysLogLoggerFactoryImpl.TSysLogLoggerFactory;
TThreadSafeLogger = ThreadSafeLoggerImpl.TThreadSafeLogger;

TDecoratorLogger = DecoratorLoggerImpl.TDecoratorLogger;
TBackgroundThreadLogger = BackgroundThreadLoggerImpl.TBackgroundThreadLogger;

TDbLogger = DbLoggerImpl.TDbLogger;
TDbLoggerFactory = DbLoggerFactoryImpl.TDbLoggerFactory;

TMailLogger = MailLoggerImpl.TMailLogger;
TMailLoggerFactory = MailLoggerFactoryImpl.TMailLoggerFactory;
