{*!
 * Fano Web Framework (https://fanoframework.github.io)
 *
 * @link      https://github.com/fanoframework/fano
 * @copyright Copyright (c) 2018 Zamrony P. Juhara
 * @license   https://github.com/fanoframework/fano/blob/master/LICENSE (MIT)
 *}

TAbstractLogger = AbstractLoggerImpl.TAbstractLogger;
TFileLogger = FileLoggerImpl.TFileLogger;
TFileLoggerFactory = FileLoggerFactoryImpl.TFileLoggerFactory;
TNullLogger = NullLoggerImpl.TNullLogger;
TNullLoggerFactory = NullLoggerFactoryImpl.TNullLoggerFactory;
TCompositeLogger = CompositeLoggerImpl.TCompositeLogger;
TCompositeLoggerFactory = CompositeLoggerFactoryImpl.TCompositeLoggerFactory;
TSegregatedLogger = SegregatedLoggerImpl.TSegregatedLogger;
TSegregatedLoggerFactory = SegregatedLoggerFactoryImpl.TSegregatedLoggerFactory;
TStdOutLogger = StdOutLoggerImpl.TStdOutLogger;
TStdOutLoggerFactory = StdOutLoggerFactoryImpl.TStdOutLoggerFactory;
TSysLogLogger = SysLogLoggerImpl.TSysLogLogger;
TSysLogLoggerFactory = SysLogLoggerFactoryImpl.TSysLogLoggerFactory;
TThreadSafeLogger = ThreadSafeLoggerImpl.TThreadSafeLogger;
TDbLogger = DbLoggerImpl.TDbLogger;
DbLoggerFactory = DbLoggerFactoryImpl.TDbLoggerFactory;
