{*!
 * Fano Web Framework (https://fanoframework.github.io)
 *
 * @link      https://github.com/fanoframework/fano
 * @copyright Copyright (c) 2018 - 2020 Zamrony P. Juhara
 * @license   https://github.com/fanoframework/fano/blob/master/LICENSE (MIT)
 *}

TBlowfishEncrypter = BlowfishEncrypterImpl.TBlowfishEncrypter;
TBlowfishEncrypterFactory = BlowfishEncrypterFactoryImpl.TBlowfishEncrypterFactory;

THmacEncrypter = HmacEncrypterImpl.THmacEncrypter;
TSha1HmacEncrypter = Sha1HmacEncrypterImpl.TSha1HmacEncrypter;
TMd5HmacEncrypter = Md5HmacEncrypterImpl.TMd5HmacEncrypter;

THmacEncrypterFactory = HmacEncrypterFactoryImpl.THmacEncrypterFactory;
TSha1BlowfishEncrypterFactory = Sha1BlowfishEncrypterFactoryImpl.TSha1BlowfishEncrypterFactory;
TMd5BlowfishEncrypterFactory = Md5BlowfishEncrypterFactoryImpl.TMd5BlowfishEncrypterFactory;
