(*! ---------------------------------------------
 * implementation unit that is included in fano.pas unit
 * This file is provided so we can use fano framework
 * by using only one uses to simplify things.
 *
 * @author Zamrony P. Juhara <zamronypj@yahoo.com>
 *-----------------------------------------------*)
DependencyContainerImpl,
DependencyListImpl,
EnvironmentImpl,
EnvironmentFactoryImpl,
ErrorHandlerImpl,
AjaxErrorHandlerImpl,
EDependencyNotFoundImpl,
EInvalidFactoryImpl,
FactoryImpl,

DispatcherFactoryImpl,
SimpleDispatcherFactoryImpl,
EInvalidDispatcherImpl,
EMethodNotAllowedImpl,
ERouteHandlerNotFoundImpl,

AppImpl,
RouteHandlerImpl,
RouteCollectionFactoryImpl,
SimpleRouteCollectionFactoryImpl,
CombineRouteCollectionFactoryImpl,

HeadersFactoryImpl,
OutputBufferFactoryImpl,
ErrorHandlerFactoryImpl,
JsonResponseImpl,
JsonFileConfigImpl,
JsonFileConfigFactoryImpl,
MiddlewareCollectionAwareFactoryImpl,
NullMiddlewareCollectionAwareFactoryImpl,
TemplateParserFactoryImpl,
SimpleTemplateParserFactoryImpl,
TemplateFileViewImpl,
ViewParametersFactoryImpl,
ControllerImpl,
FileLoggerImpl,
FileLoggerFactoryImpl,
NullLoggerImpl,
NullLoggerFactoryImpl,  //note: coma, instead of semicolon, is intentional
