IOutputBuffer = OutputBufferIntf.IOutputBuffer;
ILogger = LoggerIntf.ILogger;
IFileReader = FileReaderIntf.IFileReader;
IStreamAdapter = StreamAdapterIntf.IStreamAdapter;
IStdInReader = StdInReaderIntf.IStdInReader;
IStdOut = StdOutIntf.IStdOut;
IStdErr = StdErrIntf.IStdErr;

IHttpClientHandleAware = HttpClientHandleAwareIntf.IHttpClientHandleAware;
IHttpClientHeaders = HttpClientHeadersIntf.IHttpClientHeaders;
IHttpGetClient = HttpGetClientIntf.IHttpGetClient;
IHttpPostClient = HttpPostClientIntf.IHttpPostClient;
IHttpPutClient = HttpPutClientIntf.IHttpPutClient;
IHttpDeleteClient = HttpDeleteClientIntf.IHttpDeleteClient;
IHttpHeadClient = HttpHeadClientIntf.IHttpHeadClient;

IKeyValuePair = KeyValuePairIntf.IKeyValuePair;

IRunnableWithDataNotif = RunnableWithDataNotifIntf.IRunnableWithDataNotif;

IFcgiRecord = FcgiRecordIntf.IFcgiRecord;
IFcgiRecordFactory = FcgiRecordFactoryIntf.IFcgiRecordFactory;
IFcgiRequest = FcgiRequestIntf.IFcgiRequest;
IFcgiRequestManager = FcgiRequestManagerIntf.IFcgiRequestManager;
IFcgiFrameParser = FcgiFrameParserIntf.IFcgiFrameParser;
IFcgiProcessor = FcgiProcessorIntf.IFcgiProcessor;
