IOutputBuffer = OutputBufferIntf.IOutputBuffer;
ILogger = LoggerIntf.ILogger;
IFileReader = FileReaderIntf.IFileReader;
IStreamAdapter = StreamAdapterIntf.IStreamAdapter;
IStdInReader = StdInReaderIntf.IStdInReader;

IHttpGetClient = HttpGetClientIntf.IHttpGetClient;
IHttpPostClient = HttpPostClientIntf.IHttpPostClient;
IHttpPutClient = HttpPutClientIntf.IHttpPutClient;
IHttpDeleteClient = HttpDeleteClientIntf.IHttpDeleteClient;
IHttpHeadClient = HttpHeadClientIntf.IHttpHeadClient;

IKeyValuePair = KeyValuePairIntf.IKeyValuePair;

IFcgiFrameParser = FcgiFrameParserIntf.IFcgiFrameParser;
IFcgiRecord = FcgiRecordIntf.IFcgiRecord;
IFcgiRequest = FcgiRequestIntf.IFcgiRequest;
