IOutputBuffer = OutputBufferIntf.IOutputBuffer;
ILogger = LoggerIntf.ILogger;
IFileReader = FileReaderIntf.IFileReader;
IStreamAdapter = StreamAdapterIntf.IStreamAdapter;
IStdInReader = StdInReaderIntf.IStdInReader;

IHttpClientHandleAware = HttpClientHandleAwareIntf.IHttpClientHandleAware;
IHttpClientHeaders = HttpClientHeadersIntf.IHttpClientHeaders;
IHttpGetClient = HttpGetClientIntf.IHttpGetClient;
IHttpPostClient = HttpPostClientIntf.IHttpPostClient;
IHttpPutClient = HttpPutClientIntf.IHttpPutClient;
IHttpDeleteClient = HttpDeleteClientIntf.IHttpDeleteClient;
IHttpHeadClient = HttpHeadClientIntf.IHttpHeadClient;

IKeyValuePair = KeyValuePairIntf.IKeyValuePair;
