{*!
 * Fano Web Framework (https://fanoframework.github.io)
 *
 * @link      https://github.com/fanoframework/fano
 * @copyright Copyright (c) 2018 Zamrony P. Juhara
 * @license   https://github.com/fanoframework/fano/blob/master/LICENSE (MIT)
 *}

(*! ---------------------------------------------
 * alias for dependency container interfaces
 * that is included in fano.pas unit
 *
 * @author Zamrony P. Juhara <zamronypj@yahoo.com>
 *-----------------------------------------------*)

IDependencyContainer = DependencyContainerIntf.IDependencyContainer;
IDependencyFactory = DependencyContainerIntf.IDependencyFactory;
IDependency = DependencyIntf.IDependency;
IDependencyList = DependencyListIntf.IDependencyList;

IServiceContainer = ServiceContainerIntf.IServiceContainer;
IServiceFactory = ServiceFactoryIntf.IServiceFactory;
IService = ServiceIntf.IService;

IContainerFactory = ContainerFactoryIntf.IContainerFactory;

IServiceProvider = ServiceProviderIntf.IServiceProvider;
