{*!
 * Fano Web Framework (https://fanoframework.github.io)
 *
 * @link      https://github.com/fanoframework/fano
 * @copyright Copyright (c) 2018 - 2020 Zamrony P. Juhara
 * @license   https://github.com/fanoframework/fano/blob/master/LICENSE (MIT)
 *}

{------------ Begin TFPHttpClient-related------------------}
FpcHttpGetImpl,
FpcHttpGetFactoryImpl,

FpcHttpPostImpl,
FpcHttpPostFactoryImpl,

FpcHttpPutImpl,
FpcHttpPutFactoryImpl,

FpcHttpDeleteImpl,
FpcHttpDeleteFactoryImpl,

FpcHttpOptionsImpl,
FpcHttpOptionsFactoryImpl,

FpcHttpPatchImpl,
FpcHttpPatchFactoryImpl,

FpcHttpHeadImpl,
FpcHttpHeadFactoryImpl,

{------------ End TFPHttpClient-related------------------}
