TOutputBufferFactory = OutputBufferFactoryImpl.TOutputBufferFactory;

TFileLogger = FileLoggerImpl.TFileLogger;
TFileLoggerFactory = FileLoggerFactoryImpl.TFileLoggerFactory;
TNullLogger = NullLoggerImpl.TNullLogger;
TNullLoggerFactory = NullLoggerFactoryImpl.TNullLoggerFactory;
TCompositeLogger = CompositeLoggerImpl.TCompositeLogger;
TCompositeLoggerFactory = CompositeLoggerFactoryImpl.TCompositeLoggerFactory;

TStringFileReader = StringFileReaderImpl.TStringFileReader;
TStringFileReaderFactory = StringFileReaderFactoryImpl.TStringFileReaderFactory;

TStreamAdapter = StreamAdapterImpl.TStreamAdapter;
EInvalidStream = EInvalidStreamImpl.EInvalidStream;

TStdInReader = StdInReaderImpl.TStdInReader;
TSimpleStdInReader = SimpleStdInReaderImpl.TSimpleStdInReader;

THttpCurl = HttpCurlImpl.THttpCurl;
THttpCurlFactory = HttpCurlFactoryImpl.THttpCurlFactory;

THttpGet = HttpGetImpl.THttpGet;
THttpGetFactory = HttpGetFactoryImpl.THttpGetFactory;

THttpPost = HttpPostImpl.THttpPost;
THttpPostFactory = HttpPostFactoryImpl.THttpPostFactory;

THttpPut = HttpPutImpl.THttpPut;
THttpPutFactory = HttpPutFactoryImpl.THttpPutFactory;

THttpDelete = HttpDeleteImpl.THttpDelete;
THttpDeleteFactory = HttpDeleteFactoryImpl.THttpDeleteFactory;

THttpHead = HttpHeadImpl.THttpHead;
THttpHeadFactory = HttpHeadFactoryImpl.THttpHeadFactory;

TKeyValuePair = KeyValuePairImpl.TKeyValuePair;
TKeyValuePairFactory = KeyValuePairFactoryImpl.TKeyValuePairFactory;
